config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  
  get 'about', to: 'pages#about'
  
  resources :articles
  
  get "signup", to: "users#new"
  
  resources :users, except: [:new]
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true 
  validates :description, presence: true
  #validates :user_id, presence: true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  before_save { self.email = email.downcase } 
  validates :username, presence: true, 
            uniqueness: { case_sensitive: false }, 
            length: {minimum: 3, maximum: 25 }
            VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false },
            length: {maximum: 100 }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  
  
  def index
    @articles = Article.all
  end
  
  
  def new 
    @article = Article.new
  end
  
  def create
    @article = Article.new(article_params)
    @article.user = User.first
   if @article.save
     flash[:success] = "Article was created"
     redirect_to article_path(@article)
   else
     render 'new'
   end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
      if @article.update(article_params)
       flash[:success] = "Article was updated"
       redirect_to article_path(@article)
   else
     render 'edit'
   end
  end
   
   def destroy
     @article.destroy
     flash[:danger] = "Articale was deleted"
     redirect_to articles_path
   end


  private
  def article_params
    params.require(:article).permit(:title, :description)
  end
  
  def set_article
    @article = Article.find(params[:id])
  end
    
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "welcome to the blog about everything #{@user.username}"
      redirect_to articles_path
    else
      render 'new'
    end
    
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "user was upated"
      redirect_to articles_path
    else
      render 'edit'
    end
  end
  
  
  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= render 'share/errors', obj: @article %>

<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title, "title" %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "title of artcile", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description, "description" %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "body", autofocus: true %>
          </div>
        </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to 'cancel request and return to articles listing', articles_path %> ]
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">edit article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">listing all articles</h1>

<% @articles.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
          </div>
          <div class="article-body">
            <%= truncate(article.description, length: 75) %>
            <div class="article-meta-details">
              <small>created by: <%= aarticle.user.username if article.user %>
                                 <%= time_ago_in_words(article.created_at) %> ago,
                                 last_updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
            </div>
          </div>
         <div class="article-actions">
            <%= link_to 'edit this article', edit_article_path(article), class: "btn btn-xs btn-primary" %>
            <%= link_to 'delete this article', article_path(article), method: :delete, data: {confirm: "are you sure?"},
              class: "btn btn-xs btn-danger" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

app/views/articles/new.html.erb
<h1 align="center">create a new article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <h4 class="center description"><strong>description:</strong></h4>
  <hr>
  <%= simple_format(@article.description) %>
  <div class="article-actions">
    <%= link_to 'edit this article', edit_article_path(@article), class: "btn btn-xs btn-primary" %>
    <%= link_to 'delete this article', article_path(@article), method: :delete, data: {confirm: "are you sure?"},
          class: "btn btn-xs btn-danger" %>
    <%= link_to 'view all articles', articles_path, class: "btn btn-xs btn-success" %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      copyright &copy; a letter to kirby
    </small>
    <nav>
      <ul>
        <li><%= link_to "about", about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
    <div class='alert alert-<%="#{name}" %>'>
      <a href="#" class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'a letter to kirby', root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'articles', articles_path %></li>
        <li><a href="#">link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%=link_to 'new article', new_article_path %></li>
            <li><a href="#">another action</a></li>
            <li><a href="#">something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">one more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">action</a></li>
            <li><a href="#">another action</a></li>
            <li><a href="#">something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogck</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/pages/about.html.erb
<h1>about</h1>

<%= link_to 'home', root_path %>

app/views/pages/home.html.erb
<div class ="center jumbotron">
  <h1>a letter to kirby</h1>

  <%= link_to 'sign up now', "#", class: "btn btn-danger btn-lg btn-xlarge" %>
</div>

app/views/share/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this article from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'share/errors', obj: @user %>

<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :username, "username" %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :username, class: "form-control", placeholder: "enter username", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :email, "email" %>
        </div>
        <div class="col-sm-8">
          <%= f.email_field :email, class: "form-control", placeholder: "enter email", autofocus: true %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :password, "password" %>
          </div>
          <div class="col-sm-8">
            <%= f.password_field :password, class: "form-control", placeholder: "enter password", autofocus: true %>
          </div>
        </div> 
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit(@user.new_record? ? "signup" : "update account", class: 'btn btn-primary btn-lg') %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to 'cancel request and return to articles listing', articles_path %> ]
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">edit your account</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<h1 align="center">tell kirby what's on your mind</h1>

<%= render 'form' %>